Doc - remove "filters" import statement as it does not exist
Issuing "snactor workflow run Example" fails with:

ImportError: No module named filters

The import statement was probably introduced by mistake.