Fix exception in normalize_schemas for conflicting actor config schemas
The normalize_schemas function incorrectly raises an exception when a
config schema (subclass of Config) is contained more than once in it's
input, regardless of whether it's a conflicting (same section and name,
but a difference in other members) or the same (same section and name).
Traceback:

Traceback (most recent call last):
  File "/usr/bin/leapp", line 33, in <module>
    sys.exit(load_entry_point('leapp==0.21.0', 'console_scripts', 'leapp')())
  File "/usr/lib/python3.9/site-packages/leapp/cli/__init__.py", line 51, in main
    cli.command.execute('leapp version {}'.format(VERSION))
  File "/usr/lib/python3.9/site-packages/leapp/utils/clicmd.py", line 111, in execute
    args.func(args)
  File "/usr/lib/python3.9/site-packages/leapp/utils/clicmd.py", line 133, in called
    self.target(args)
  File "/usr/lib/python3.9/site-packages/leapp/cli/commands/upgrade/breadcrumbs.py", line 169, in wrapper
    return f(*args, breadcrumbs=breadcrumbs, **kwargs)
  File "/usr/lib/python3.9/site-packages/leapp/cli/commands/preupgrade/__init__.py", line 86, in preupgrade
    command_utils.load_actor_configs_and_store_it_in_db(context, repositories, cfg)
  File "/usr/lib/python3.9/site-packages/leapp/cli/commands/command_utils.py", line 291, in load_actor_configs_and_store_it_in_db
    actor_config_schemas = actor_config.normalize_schemas(actor_config_schemas)
  File "/usr/lib/python3.9/site-packages/leapp/actors/config.py", line 180, in normalize_schemas
    if unique_name in added_fields and added_fields[unique_name] != field:
TypeError: 'set' object is not subscriptable

The added_fields variable is a set. The condition for checking conflicts
attempts to do indexing on the set, which is not possible in Python sets
and results in a TypeError.

This patch removes the set altogether since it doesn't bring any
advantage over just using the normalized_schemas dict.

Also add unit tests for the function.